name: VIDEO ENHANCER

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST
    - cron: '30 6 * * *'   # 12:00 PM IST
    - cron: '30 9 * * *'   # 3:00 PM IST
    - cron: '30 12 * * *'  # 6:00 PM IST
    - cron: '30 15 * * *'  # 9:00 PM IST

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            video_enhancer/
            counter.txt
            requirements.txt
          fetch-depth: 1

      # Read the counter value and set sparse-checkout for the specific video
      - name: Configure Sparse Checkout for Specific Video
        run: |
          VIDEO_NUMBER=$(cat counter.txt)
          echo "Setting sparse-checkout for Video_${VIDEO_NUMBER}.mp4"
          echo "private/videos/Video_${VIDEO_NUMBER}.mp4" >> .git/info/sparse-checkout
          git sparse-checkout reapply

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need
      
      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        run: python3 video_enhancer/video_enhancer.py

      # Configure sparse checkout for public/videos and commit only the new file
      - name: Sparse Checkout and Commit Changes
        run: |
          VIDEO_NUMBER=$(cat counter.txt)
          ENHANCED_VIDEO="public/videos/Video_${VIDEO_NUMBER}.mp4"
          echo "Setting sparse-checkout for ${ENHANCED_VIDEO}"
          echo "${ENHANCED_VIDEO}" >> .git/info/sparse-checkout
          git sparse-checkout reapply
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add "${ENHANCED_VIDEO}"
          git commit -m "Update ${ENHANCED_VIDEO} after processing" || echo "No changes to commit"
          git pull --rebase origin main || echo "No changes to pull"
          git push || echo "No changes to push"